### ISSUE TITLE
Adding new Feature 

### ISSUE THREAD

**Issue by mahdy151** [mpiorowski/rusve#26]
Hi
Thanks you for the stack and effort 
I was thinking it would be nice to have a full blown wysiwyg editor for post and gallery file upload. somthing like a cms for a small blog site.

**Comment by mpiorowski** [comment]
Good idea, adding to the list ;)

**Comment by mpiorowski** [comment]
Wyswig ready, without file upload, but can be easily achieved with tiptap ->
https://www.codemzy.com/blog/tiptap-drag-drop-image

working on cms

**Comment by mpiorowski** [comment]
Added headless cms setup :)
