### ISSUE TITLE
Sorry to bother again 

### ISSUE THREAD

**Issue by mahdy151** [mpiorowski/rusve#27]
Hi again
im working on same concept but struggling in the frontend side, it would be super nice if you have the time to write a medium article about project structure and the source you used.
Thanks alot

**Comment by mpiorowski** [comment]
Would love too, but i suck at writing articles :D Also making a really good article that have sense takes a lot of time, which currently i am lacking a little ;p

**Comment by mahdy151** [comment]
Dont worry, take your time
Thanks
