### ISSUE TITLE
Why the hell Rust is a little bit slower then Go?

### ISSUE THREAD

**Issue by mpiorowski** [mpiorowski/rusve#31]
So maybe somebody can help me out here, 

Create a 10000 notes / posts and try to request them.

Go have a little time advantage here..... And i feel like it should be the other way around. Maybe somebody have an idea why is that? Go works better with gRPC? Rust async threads are a little worse? 

Will make a live benchmark inside www.rusve.app so everyone can check this out.

**Comment by mpiorowski** [comment]
Ok, i changed the sqlx create to tokio-postgres, now the diffrence is much smaller, but still....go wins almost every time...

**Comment by liamwh** [comment]
Hey @mpiorowski, great question! This is exactly the sort of question telemetry can answer, if you instrument your services and visualise the traces in something like Jaeger or Tempo, you can see how long each span takes (like in the image below) and find your exact answer!
![image](https://github.com/mpiorowski/rusve/assets/23312359/3c99f255-385a-424b-bdc5-7285b4f947ab)

On another note, do you know what it was about sqlx that caused performance issues?

**Comment by mpiorowski** [comment]
I did some testing, and with higher traffic the rust beats go, not by a big margin but still :)
